INSERT INTO Level (Description) VALUES('Ομότιμος Καθηγητής')
INSERT INTO Level (Description) VALUES('Καθηγητής (Α` Βαθμίδας)')
INSERT INTO Level (Description) VALUES('Αναπληρωτής Καθηγητής')
INSERT INTO Level (Description) VALUES('Επίκουρος Καθηγητής')
INSERT INTO Level (Description) VALUES('Καθηγητής Εφαρμογών')