INSERT INTO Courses ( Course_type_idCourse_type, Title, Semester) VALUES(1,'Θεωρία Πιθανοτήτων',1)
INSERT INTO Courses ( Course_type_idCourse_type, Title, Semester) VALUES(1,'Μαθηματική Ανάλυση και Στοιχεία Γραμμικής Άλγεβρας',1)
INSERT INTO Courses ( Course_type_idCourse_type, Title, Semester) VALUES(1,'Γλώσσα Προγραμματισμού C',1)
INSERT INTO Courses ( Course_type_idCourse_type, Title, Semester) VALUES(1,'Αντικειμενοστρεφής Προγραμματισμός',2)
INSERT INTO Courses ( Course_type_idCourse_type, Title, Semester) VALUES(1,'Στοχαστικές Ανελίξεις',2)
INSERT INTO Courses ( Course_type_idCourse_type, Title, Semester) VALUES(1,'Δομές Δεδομένων',3)
INSERT INTO Courses ( Course_type_idCourse_type, Title, Semester) VALUES(1,'Τεχνολογία Λογισμικού',3)
INSERT INTO Courses ( Course_type_idCourse_type, Title, Semester) VALUES(1,'Σχεδιασμός Βάσεων Δεδομένων',4)
INSERT INTO Courses ( Course_type_idCourse_type, Title, Semester) VALUES(1,'Αλγόριθμοι και Πολυπλοκότητα',4)
INSERT INTO Courses ( Course_type_idCourse_type, Title, Semester) VALUES(1,'Τεχνητή Νοημοσύνη',5)
INSERT INTO Courses ( Course_type_idCourse_type, Title, Semester) VALUES(1,'Ευρυζωνικά Δίκτυα',5)
INSERT INTO Courses ( Course_type_idCourse_type, Title, Semester) VALUES(1,'Μεταγλωττιστές',5)
INSERT INTO Courses ( Course_type_idCourse_type, Title, Semester) VALUES(1,'Πληροφοριακά Συστήματα',6)
INSERT INTO Courses ( Course_type_idCourse_type, Title, Semester) VALUES(1,'Τεχνικές Βελτιστοποίησης',6)
INSERT INTO Courses ( Course_type_idCourse_type, Title, Semester) VALUES(1,'Αναγνώριση Προτύπων',7)
INSERT INTO Courses ( Course_type_idCourse_type, Title, Semester) VALUES(1,'Διαλειτουργικότητα Συστημάτων',7)
INSERT INTO Courses ( Course_type_idCourse_type, Title, Semester) VALUES(1,'Αποθήκες και Εξόρυξη Δεδομένων',8)
INSERT INTO Courses ( Course_type_idCourse_type, Title, Semester) VALUES(1,'Τηλεϊατρική',8)
INSERT INTO Courses ( Course_type_idCourse_type, Title, Semester) VALUES(1,'Προχωρημένα Θέματα Ασύρματων Επικοινωνιών',8)
INSERT INTO Courses ( Course_type_idCourse_type, Title, Semester) VALUES(2,'Η Γλώσσα Προγραμματισμού Python',1)
INSERT INTO Courses ( Course_type_idCourse_type, Title, Semester) VALUES(2,'Διαχείριση Δεδομένων για Σχεσιακές και μη Σχεσιακές Βάσεις Δεδομένων    ',1)
INSERT INTO Courses ( Course_type_idCourse_type, Title, Semester) VALUES(2,'Μηχανική Μάθηση: Μέθοδοι και Αλγόριθμοι',1)
INSERT INTO Courses ( Course_type_idCourse_type, Title, Semester) VALUES(2,'Εξόρυξη και Προετοιμασία Δεδομένων',1)
INSERT INTO Courses ( Course_type_idCourse_type, Title, Semester) VALUES(2,'Μεγάλα Δεδομένα και Αναλυτική ΙΙ: Τεχνικές και Εργαλεία',2)
INSERT INTO Courses ( Course_type_idCourse_type, Title, Semester) VALUES(2,'Αναλυτική Επιχειρησιακών Διεργασιών',2)
INSERT INTO Courses ( Course_type_idCourse_type, Title, Semester) VALUES(2,'Εφαρμογές Αναλυτικής Μεγάλων Δεδομένων',2)
INSERT INTO Courses ( Course_type_idCourse_type, Title, Semester) VALUES(2,'Πρακτική Μηχανική Μάθηση',2)